# Generated by Django 2.2 on 2021-04-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=80)),
                ('userr2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requset_frinend', models.CharField(max_length=20)),
                ('request_to', models.CharField(max_length=20)),
                ('accepted_friend', models.CharField(max_length=20)),
                ('accepted_to', models.CharField(max_length=20)),
                ('nos_friends', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('userr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textmess', models.CharField(max_length=400)),
                ('usersend', models.CharField(max_length=20)),
                ('userto', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('mon', models.IntegerField()),
                ('day', models.IntegerField()),
                ('Hour', models.IntegerField()),
                ('mins', models.IntegerField()),
                ('sec', models.IntegerField()),
            ],
        ),
    ]
